import { ascii } from "@/lib/demo/yamaha/protocol-utils"

const u16le = (value: number) => [value & 0xff, (value >> 8) & 0xff]
const u32le = (value: number) => [
  value & 0xff,
  (value >> 8) & 0xff,
  (value >> 16) & 0xff,
  (value >> 24) & 0xff,
]

/**
 * Minimal Yamaha YRGN registration bank with slot 1 pointing to a style path.
 * The chunk layout is based on the Genos registration generated by the
 * desktop proof-of-concept: YRGN / SLOT / STYL / ENDR.
 */
export function createStylePreviewRegistration(stylePath: string): Uint8Array {
  const normalizedPath = stylePath.replace(/\//g, "\\")
  if (!/^\d+:\\STYLE\\/i.test(normalizedPath)) {
    throw new Error("Registration style path must point inside the keyboard STYLE folder.")
  }

  const path = ascii(normalizedPath)
  if (!path.length || path.length > 255) {
    throw new Error("The keyboard style path is too long.")
  }

  return Uint8Array.from([
    ...ascii("YRGN"),
    0x01,
    0x00,
    0x00,
    0x00,
    0x01,
    0x00,
    ...ascii("SLOT"),
    0x01,
    0x01,
    ...ascii("STYL"),
    ...u32le(path.length + 2),
    ...u16le(path.length),
    ...path,
    ...ascii("ENDR"),
  ])
}
