import type { JamSong, JamStyleSummary } from "../types"

/** Compact paid-UI fixtures — exact source section names, Main A–D only. */
export const FIXTURE_SONGS: JamSong[] = [
  {
    id: "song-coastal-drive",
    title: "Coastal Drive",
    subtitle: "Bright Pop factory arrangement",
    category: "Pop",
    tempo: 112,
    key: "C",
    timeSignature: [4, 4],
    accent: "#38bdf8",
    sections: [
      {
        id: "sec-verse",
        label: "Verse",
        bars: 8,
        variation: "A",
        chords: [
          { beat: 0, duration: 4, name: "Cmaj7" },
          { beat: 4, duration: 4, name: "Am7" },
          { beat: 8, duration: 4, name: "Fmaj7" },
          { beat: 12, duration: 4, name: "G7" },
          { beat: 16, duration: 4, name: "Cmaj7" },
          { beat: 20, duration: 4, name: "Am7" },
          { beat: 24, duration: 4, name: "Dm7" },
          { beat: 28, duration: 4, name: "G7" },
        ],
      },
      {
        id: "sec-chorus",
        label: "Chorus",
        bars: 8,
        variation: "B",
        chords: [
          { beat: 0, duration: 4, name: "Fmaj7" },
          { beat: 4, duration: 4, name: "G7" },
          { beat: 8, duration: 4, name: "Em7" },
          { beat: 12, duration: 4, name: "Am7" },
          { beat: 16, duration: 4, name: "Dm7" },
          { beat: 20, duration: 4, name: "G7" },
          { beat: 24, duration: 4, name: "Cmaj7" },
          { beat: 28, duration: 4, name: "G7" },
        ],
      },
      {
        id: "sec-bridge",
        label: "Bridge",
        bars: 4,
        variation: "C",
        chords: [
          { beat: 0, duration: 4, name: "Bbmaj7" },
          { beat: 4, duration: 4, name: "Fmaj7" },
          { beat: 8, duration: 4, name: "Em7" },
          { beat: 12, duration: 4, name: "A7" },
        ],
      },
    ],
    reharmonizations: [
      {
        id: "Pop",
        label: "Pop",
        chordsBySection: {
          "sec-verse": [
            { beat: 0, duration: 4, name: "C" },
            { beat: 4, duration: 4, name: "G/B" },
            { beat: 8, duration: 4, name: "Am" },
            { beat: 12, duration: 4, name: "F" },
            { beat: 16, duration: 4, name: "C" },
            { beat: 20, duration: 4, name: "G/B" },
            { beat: 24, duration: 4, name: "Am" },
            { beat: 28, duration: 4, name: "G" },
          ],
          "sec-chorus": [
            { beat: 0, duration: 4, name: "F" },
            { beat: 4, duration: 4, name: "C" },
            { beat: 8, duration: 4, name: "Dm" },
            { beat: 12, duration: 4, name: "G" },
            { beat: 16, duration: 4, name: "F" },
            { beat: 20, duration: 4, name: "C" },
            { beat: 24, duration: 4, name: "G" },
            { beat: 28, duration: 4, name: "C" },
          ],
        },
      },
      {
        id: "Rock",
        label: "Rock",
        chordsBySection: {
          "sec-verse": [
            { beat: 0, duration: 4, name: "C5" },
            { beat: 4, duration: 4, name: "Am" },
            { beat: 8, duration: 4, name: "F5" },
            { beat: 12, duration: 4, name: "G5" },
            { beat: 16, duration: 4, name: "C5" },
            { beat: 20, duration: 4, name: "Am" },
            { beat: 24, duration: 4, name: "Dm" },
            { beat: 28, duration: 4, name: "G5" },
          ],
        },
      },
    ],
  },
  {
    id: "song-midnight-lane",
    title: "Midnight Lane",
    subtitle: "Laid-back Ballad factory arrangement",
    category: "Ballad",
    tempo: 72,
    key: "F",
    timeSignature: [4, 4],
    accent: "#c084fc",
    sections: [
      {
        id: "sec-intro",
        label: "Intro",
        bars: 4,
        variation: "A",
        chords: [
          { beat: 0, duration: 4, name: "Fmaj9" },
          { beat: 4, duration: 4, name: "Dm9" },
          { beat: 8, duration: 4, name: "Gm9" },
          { beat: 12, duration: 4, name: "C13" },
        ],
      },
      {
        id: "sec-verse-a",
        label: "Verse",
        bars: 8,
        variation: "B",
        chords: [
          { beat: 0, duration: 4, name: "Fmaj9" },
          { beat: 4, duration: 4, name: "Am7" },
          { beat: 8, duration: 4, name: "Bbmaj7" },
          { beat: 12, duration: 4, name: "C7sus" },
          { beat: 16, duration: 4, name: "Fmaj9" },
          { beat: 20, duration: 4, name: "Dm9" },
          { beat: 24, duration: 4, name: "Gm9" },
          { beat: 28, duration: 4, name: "C13" },
        ],
      },
      {
        id: "sec-chorus-a",
        label: "Chorus",
        bars: 8,
        variation: "D",
        chords: [
          { beat: 0, duration: 4, name: "Bbmaj7" },
          { beat: 4, duration: 4, name: "Am7" },
          { beat: 8, duration: 4, name: "Gm9" },
          { beat: 12, duration: 4, name: "C13" },
          { beat: 16, duration: 4, name: "Fmaj9" },
          { beat: 20, duration: 4, name: "Dm9" },
          { beat: 24, duration: 4, name: "Gm9" },
          { beat: 28, duration: 4, name: "C13" },
        ],
      },
    ],
    reharmonizations: [],
  },
  {
    id: "song-harbor-swing",
    title: "Harbor Swing",
    subtitle: "Swing & Jazz factory arrangement",
    category: "Swing & Jazz",
    tempo: 132,
    key: "Bb",
    timeSignature: [4, 4],
    accent: "#fbbf24",
    sections: [
      {
        id: "sec-head",
        label: "Head",
        bars: 8,
        variation: "A",
        chords: [
          { beat: 0, duration: 4, name: "Bb6" },
          { beat: 4, duration: 4, name: "G7" },
          { beat: 8, duration: 4, name: "Cm7" },
          { beat: 12, duration: 4, name: "F7" },
          { beat: 16, duration: 4, name: "Dm7" },
          { beat: 20, duration: 4, name: "G7" },
          { beat: 24, duration: 4, name: "Cm7" },
          { beat: 28, duration: 4, name: "F7" },
        ],
      },
      {
        id: "sec-solo",
        label: "Solo",
        bars: 8,
        variation: "C",
        chords: [
          { beat: 0, duration: 4, name: "Bb6" },
          { beat: 4, duration: 4, name: "Bb7" },
          { beat: 8, duration: 4, name: "Ebmaj7" },
          { beat: 12, duration: 4, name: "Edim7" },
          { beat: 16, duration: 4, name: "Bb6" },
          { beat: 20, duration: 4, name: "G7" },
          { beat: 24, duration: 4, name: "Cm7" },
          { beat: 28, duration: 4, name: "F7" },
        ],
      },
    ],
    reharmonizations: [],
  },
]

export const FIXTURE_STYLES: JamStyleSummary[] = [
  { id: "style-easypop", name: "EasyPop", category: "Pop", styleNumber: 12, bpm: 112 },
  { id: "style-6to8pop", name: "6/8PopBallad", category: "Ballad", styleNumber: 28, bpm: 72 },
  { id: "style-swingfox", name: "SwingFox", category: "Swing & Jazz", styleNumber: 64, bpm: 132 },
  { id: "style-cooljazz", name: "CoolJazz", category: "Swing & Jazz", styleNumber: 71, bpm: 110 },
  { id: "style-gospel", name: "GospelShuffle", category: "Gospel", styleNumber: 88, bpm: 96 },
  { id: "style-funk", name: "FunkyGuitar", category: "R&B", styleNumber: 102, bpm: 100 },
]

export const KEY_OPTIONS = [
  "C",
  "C#",
  "Db",
  "D",
  "Eb",
  "E",
  "F",
  "F#",
  "Gb",
  "G",
  "Ab",
  "A",
  "Bb",
  "B",
] as const
