import { PILOT_PROGRESSIONS } from "@/lib/band-jam/progressions"
import { PILOT_STYLES } from "@/lib/band-jam/styles"
import type { BandJamCatalog, StemPackMeta } from "@/lib/band-jam/types"
import generatedPacks from "@/lib/band-jam/packs.generated.json"

/**
 * Packs pre-rendered with the PSR-S900 SFZ pipeline (sfizz).
 * Regenerated by: Smartbridge/scripts/band_jam_pilot/batch_render.py
 */
export const RENDERED_PACKS: StemPackMeta[] = generatedPacks as StemPackMeta[]

export function getBandJamCatalog(): BandJamCatalog {
  return {
    styles: PILOT_STYLES,
    progressions: PILOT_PROGRESSIONS,
    packs: RENDERED_PACKS,
  }
}

export function packIdFor(opts: {
  styleId: string
  progressionId: string
  keyPc: number
  tempo: number
}): string {
  return `${opts.styleId}__${opts.progressionId}__k${opts.keyPc}__t${opts.tempo}`
}

export function findPack(
  catalog: BandJamCatalog,
  opts: { styleId: string; progressionId: string; keyPc: number; tempo: number },
): StemPackMeta | undefined {
  const id = packIdFor(opts)
  return catalog.packs.find((p) => p.packId === id)
}

/** Packs available for a style + progression (any key/tempo). */
export function packsFor(
  catalog: BandJamCatalog,
  styleId: string,
  progressionId: string,
): StemPackMeta[] {
  return catalog.packs.filter(
    (p) => p.styleId === styleId && p.progressionId === progressionId,
  )
}

