/** Ported from BassMegaVoiceMaps / GuitarMegaVoiceMaps (desktop).
 *  Drum kits: genos2 rows from keyboard_voices where category/sub_category = DrumKit
 *  (SmartBridge/Resources/smartbridge.db) — do not invent kit names. */
import type { XgVoice } from "@/lib/style-maker/audition-voice"

export type VoiceChoice = XgVoice & { id: string; group: string }

export const BASS_MEGAVOICE_CHOICES: VoiceChoice[] = [
  { id: "AcousticBass", label: "AcousticBass", msb: 8, lsb: 0, programYamaha: 17, group: "MegaVoice Bass" },
  { id: "ElectricBass", label: "ElectricBass", msb: 8, lsb: 0, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "VintageRoundBass", label: "VintageRoundBass", msb: 8, lsb: 1, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "VintageFlatBass", label: "VintageFlatBass", msb: 8, lsb: 2, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "PickBass", label: "PickBass", msb: 8, lsb: 0, programYamaha: 19, group: "MegaVoice Bass" },
  { id: "VintagePickBass", label: "VintagePickBass", msb: 8, lsb: 1, programYamaha: 19, group: "MegaVoice Bass" },
  { id: "FretlessBass", label: "FretlessBass", msb: 8, lsb: 0, programYamaha: 20, group: "MegaVoice Bass" },
  { id: "ActiveBassFingHarm", label: "ActiveBassFingHarm", msb: 8, lsb: 4, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ActiveBassFingSlap", label: "ActiveBassFingSlap", msb: 8, lsb: 5, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ActiveBassPick", label: "ActiveBassPick", msb: 8, lsb: 3, programYamaha: 19, group: "MegaVoice Bass" },
  { id: "ActiveBassPickOpen", label: "ActiveBassPickOpen", msb: 8, lsb: 4, programYamaha: 19, group: "MegaVoice Bass" },
  { id: "ActiveBassPickMute", label: "ActiveBassPickMute", msb: 8, lsb: 5, programYamaha: 19, group: "MegaVoice Bass" },
  { id: "ActiveBassFingHmrOn", label: "ActiveBassFingHmrOn", msb: 8, lsb: 3, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ActiveBassPickHmrOn", label: "ActiveBassPickHmrOn", msb: 8, lsb: 2, programYamaha: 19, group: "MegaVoice Bass" },
  { id: "ActiveBassSlap", label: "ActiveBassSlap", msb: 8, lsb: 0, programYamaha: 21, group: "MegaVoice Bass" },
  { id: "OberkrainerBassTuba", label: "OberkrainerBassTuba", msb: 8, lsb: 2, programYamaha: 59, group: "MegaVoice Bass" },
  { id: "ElJazzFingerMute", label: "ElJazzFingerMute", msb: 8, lsb: 6, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ElJazzPickMute", label: "ElJazzPickMute", msb: 8, lsb: 7, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ElJazzPickOpen", label: "ElJazzPickOpen", msb: 8, lsb: 8, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ElJazzSlapCompatible", label: "ElJazzSlapCompatible", msb: 8, lsb: 9, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ElJazzFingerOpenMute", label: "ElJazzFingerOpenMute", msb: 8, lsb: 12, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ElJazzFingerOpenHarm", label: "ElJazzFingerOpenHarm", msb: 8, lsb: 13, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ElJazzFingerOpenSlap", label: "ElJazzFingerOpenSlap", msb: 8, lsb: 14, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "ElJazzPickOpenMute", label: "ElJazzPickOpenMute", msb: 8, lsb: 6, programYamaha: 19, group: "MegaVoice Bass" },
  { id: "ElJazzFingerMuteHmr", label: "ElJazzFingerMuteHmr", msb: 8, lsb: 0, programYamaha: 22, group: "MegaVoice Bass" },
  { id: "ElJazzFingerOpenHmr", label: "ElJazzFingerOpenHmr", msb: 8, lsb: 2, programYamaha: 22, group: "MegaVoice Bass" },
  { id: "ElJazzPickMuteHmr", label: "ElJazzPickMuteHmr", msb: 8, lsb: 4, programYamaha: 22, group: "MegaVoice Bass" },
  { id: "ElJazzPickOpenHmr", label: "ElJazzPickOpenHmr", msb: 8, lsb: 6, programYamaha: 22, group: "MegaVoice Bass" },
  { id: "ElJazzSlapFull", label: "ElJazzSlapFull", msb: 8, lsb: 0, programYamaha: 23, group: "MegaVoice Bass" },
  { id: "VlBassPickMute", label: "VlBassPickMute", msb: 8, lsb: 10, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "VlBassPickOpen", label: "VlBassPickOpen", msb: 8, lsb: 11, programYamaha: 18, group: "MegaVoice Bass" },
  { id: "VlBassPickOpenMute", label: "VlBassPickOpenMute", msb: 8, lsb: 7, programYamaha: 19, group: "MegaVoice Bass" },
  { id: "VlBassPickMuteHmr", label: "VlBassPickMuteHmr", msb: 8, lsb: 8, programYamaha: 22, group: "MegaVoice Bass" },
  { id: "VlBassPickOpenHmr", label: "VlBassPickOpenHmr", msb: 8, lsb: 10, programYamaha: 22, group: "MegaVoice Bass" },
  { id: "AcJazzOpenExtended2", label: "AcJazzOpenExtended2", msb: 8, lsb: 0, programYamaha: 15, group: "MegaVoice Bass" },
  { id: "AcJazzOpenExtended1", label: "AcJazzOpenExtended1", msb: 8, lsb: 0, programYamaha: 16, group: "MegaVoice Bass" },
  { id: "AcJazzMuteCompatible", label: "AcJazzMuteCompatible", msb: 8, lsb: 5, programYamaha: 17, group: "MegaVoice Bass" },
  { id: "AcJazzOpenCompatible", label: "AcJazzOpenCompatible", msb: 8, lsb: 6, programYamaha: 17, group: "MegaVoice Bass" },
  { id: "RBillyBassFingerOpen", label: "RBillyBassFingerOpen", msb: 8, lsb: 3, programYamaha: 17, group: "MegaVoice Bass" },
  { id: "RBillyBassSlap", label: "RBillyBassSlap", msb: 8, lsb: 4, programYamaha: 17, group: "MegaVoice Bass" },
  { id: "RBillyBassFingerSlap", label: "RBillyBassFingerSlap", msb: 8, lsb: 0, programYamaha: 24, group: "MegaVoice Bass" },
  { id: "MonoUprightBass", label: "MonoUprightBass", msb: 8, lsb: 2, programYamaha: 17, group: "MegaVoice Bass" },
]

export const GUITAR_MEGAVOICE_CHOICES: VoiceChoice[] = [
  { id: "NylonGuitar", label: "NylonGuitar (Acoustic)", msb: 8, lsb: 0, programYamaha: 1, group: "Acoustic" },
  { id: "ClassicNylonOpen", label: "ClassicNylonOpen (Acoustic)", msb: 8, lsb: 6, programYamaha: 1, group: "Acoustic" },
  { id: "ClassicNylonNeck", label: "ClassicNylonNeck (Acoustic)", msb: 8, lsb: 7, programYamaha: 1, group: "Acoustic" },
  { id: "ClNylonTirandoOpen", label: "ClNylonTirandoOpen (Acoustic)", msb: 8, lsb: 0, programYamaha: 9, group: "Acoustic" },
  { id: "ClNylonTirandoNeck", label: "ClNylonTirandoNeck (Acoustic)", msb: 8, lsb: 1, programYamaha: 9, group: "Acoustic" },
  { id: "FlamencoGuitar", label: "FlamencoGuitar (Acoustic)", msb: 8, lsb: 3, programYamaha: 1, group: "Acoustic" },
  { id: "SpanishMedium", label: "SpanishMedium (Acoustic)", msb: 8, lsb: 4, programYamaha: 1, group: "Acoustic" },
  { id: "SpanishHard", label: "SpanishHard (Acoustic)", msb: 8, lsb: 5, programYamaha: 1, group: "Acoustic" },
  { id: "SteelGuitar", label: "SteelGuitar (Acoustic)", msb: 8, lsb: 0, programYamaha: 2, group: "Acoustic" },
  { id: "SteelGuitarTwin1", label: "SteelGuitarTwin1 (Acoustic)", msb: 8, lsb: 5, programYamaha: 2, group: "Acoustic" },
  { id: "SteelGuitarTwin2", label: "SteelGuitarTwin2 (Acoustic)", msb: 8, lsb: 6, programYamaha: 2, group: "Acoustic" },
  { id: "SteelAcousticPick", label: "SteelAcousticPick (Acoustic)", msb: 8, lsb: 1, programYamaha: 2, group: "Acoustic" },
  { id: "SteelAcousticSlap", label: "SteelAcousticSlap (Acoustic)", msb: 8, lsb: 2, programYamaha: 2, group: "Acoustic" },
  { id: "SteelAcousticFinger", label: "SteelAcousticFinger (Acoustic)", msb: 8, lsb: 11, programYamaha: 2, group: "Acoustic" },
  { id: "SteelAcThumbPick", label: "SteelAcThumbPick (Acoustic)", msb: 8, lsb: 12, programYamaha: 2, group: "Acoustic" },
  { id: "D-FolkGuitar", label: "D-FolkGuitar (Acoustic)", msb: 8, lsb: 10, programYamaha: 2, group: "Acoustic" },
  { id: "D&HardFolkTwin1", label: "D&HardFolkTwin1 (Acoustic)", msb: 8, lsb: 13, programYamaha: 2, group: "Acoustic" },
  { id: "D&HardFolkTwin2", label: "D&HardFolkTwin2 (Acoustic)", msb: 8, lsb: 15, programYamaha: 2, group: "Acoustic" },
  { id: "D&WarmFolkTwin1", label: "D&WarmFolkTwin1 (Acoustic)", msb: 8, lsb: 14, programYamaha: 2, group: "Acoustic" },
  { id: "D&WarmFolkTwin2", label: "D&WarmFolkTwin2 (Acoustic)", msb: 8, lsb: 16, programYamaha: 2, group: "Acoustic" },
  { id: "12StringGuitar", label: "12StringGuitar (Acoustic)", msb: 8, lsb: 1, programYamaha: 3, group: "Acoustic" },
  { id: "12StringPickTwin1", label: "12StringPickTwin1 (Acoustic)", msb: 8, lsb: 7, programYamaha: 2, group: "Acoustic" },
  { id: "12StringPickTwin2", label: "12StringPickTwin2 (Acoustic)", msb: 8, lsb: 8, programYamaha: 2, group: "Acoustic" },
  { id: "HiStringGuitar", label: "HiStringGuitar (Acoustic)", msb: 8, lsb: 0, programYamaha: 3, group: "Acoustic" },
  { id: "OberkrainerGuitar", label: "OberkrainerGuitar (Acoustic)", msb: 8, lsb: 0, programYamaha: 8, group: "Acoustic" },
  { id: "Mandolin", label: "Mandolin (Acoustic)", msb: 8, lsb: 4, programYamaha: 13, group: "Acoustic" },
  { id: "UkleleThumbDown", label: "UkleleThumbDown (Acoustic)", msb: 8, lsb: 0, programYamaha: 14, group: "Acoustic" },
  { id: "CleanGuitar", label: "CleanGuitar (Electric)", msb: 8, lsb: 0, programYamaha: 4, group: "Electric" },
  { id: "SolidGuitar1", label: "SolidGuitar1 (Electric)", msb: 8, lsb: 1, programYamaha: 4, group: "Electric" },
  { id: "SolidGuitar2", label: "SolidGuitar2 (Electric)", msb: 8, lsb: 2, programYamaha: 4, group: "Electric" },
  { id: "SingleCoilGuitar", label: "SingleCoilGuitar (Electric)", msb: 8, lsb: 3, programYamaha: 4, group: "Electric" },
  { id: "JazzGuitar", label: "JazzGuitar (Electric)", msb: 8, lsb: 0, programYamaha: 7, group: "Electric" },
  { id: "SlapAmpGuitar", label: "SlapAmpGuitar (Electric)", msb: 8, lsb: 8, programYamaha: 4, group: "Electric" },
  { id: "50sVintageFinger", label: "50sVintageFinger (Electric)", msb: 8, lsb: 4, programYamaha: 4, group: "Electric" },
  { id: "50sVintageFingerSlap", label: "50sVintageFingerSlap (Electric)", msb: 8, lsb: 5, programYamaha: 4, group: "Electric" },
  { id: "50sVintagePick", label: "50sVintagePick (Electric)", msb: 8, lsb: 6, programYamaha: 4, group: "Electric" },
  { id: "50sVintageSlap", label: "50sVintageSlap (Electric)", msb: 8, lsb: 7, programYamaha: 4, group: "Electric" },
  { id: "60sVintage", label: "60sVintage (Electric)", msb: 8, lsb: 10, programYamaha: 4, group: "Electric" },
  { id: "60sVintageSlap", label: "60sVintageSlap (Electric)", msb: 8, lsb: 11, programYamaha: 4, group: "Electric" },
  { id: "OverdriveGuitar", label: "OverdriveGuitar (Electric)", msb: 8, lsb: 0, programYamaha: 5, group: "Electric" },
  { id: "DistortionGuitar", label: "DistortionGuitar (Electric)", msb: 8, lsb: 0, programYamaha: 6, group: "Electric" },
]

export const DRUM_KIT_CHOICES: VoiceChoice[] = [
  { id: "RockKit", label: "RockKit", msb: 127, lsb: 9, programYamaha: 18, group: "DrumKit" },
  { id: "PopKit", label: "PopKit", msb: 127, lsb: 9, programYamaha: 74, group: "DrumKit" },
  { id: "VintageOpenKit", label: "VintageOpenKit", msb: 127, lsb: 9, programYamaha: 75, group: "DrumKit" },
  { id: "VintageMuteKit", label: "VintageMuteKit", msb: 127, lsb: 9, programYamaha: 78, group: "DrumKit" },
  { id: "JazzStickKit", label: "JazzStickKit", msb: 127, lsb: 9, programYamaha: 79, group: "DrumKit" },
  { id: "JazzBrushExtended", label: "JazzBrushExtended", msb: 127, lsb: 9, programYamaha: 77, group: "DrumKit" },
  { id: "CinematicPercussion", label: "CinematicPercussion", msb: 126, lsb: 9, programYamaha: 51, group: "DrumKit" },
  { id: "ProductionKit", label: "ProductionKit", msb: 127, lsb: 9, programYamaha: 82, group: "DrumKit" },
  { id: "DirtyKit", label: "DirtyKit", msb: 127, lsb: 9, programYamaha: 83, group: "DrumKit" },
  { id: "IndustrialKit", label: "IndustrialKit", msb: 126, lsb: 0, programYamaha: 34, group: "DrumKit" },
  { id: "TrapKit", label: "TrapKit", msb: 127, lsb: 0, programYamaha: 115, group: "DrumKit" },
  { id: "ClubKit", label: "ClubKit", msb: 127, lsb: 0, programYamaha: 116, group: "DrumKit" },
  { id: "Chillkit", label: "Chillkit", msb: 127, lsb: 0, programYamaha: 117, group: "DrumKit" },
  { id: "PunchyEDM Kit", label: "PunchyEDM Kit", msb: 127, lsb: 0, programYamaha: 84, group: "DrumKit" },
  { id: "TightEDM Kit", label: "TightEDM Kit", msb: 127, lsb: 8, programYamaha: 118, group: "DrumKit" },
  { id: "JazzBrushKit", label: "JazzBrushKit", msb: 127, lsb: 9, programYamaha: 76, group: "DrumKit" },
  { id: "SymphonicPercussion", label: "SymphonicPercussion", msb: 127, lsb: 9, programYamaha: 49, group: "DrumKit" },
  { id: "AfroCubanKit", label: "AfroCubanKit", msb: 126, lsb: 8, programYamaha: 43, group: "DrumKit" },
  { id: "BrazilianKit", label: "BrazilianKit", msb: 126, lsb: 8, programYamaha: 120, group: "DrumKit" },
  { id: "PopPercussionKit", label: "PopPercussionKit", msb: 126, lsb: 8, programYamaha: 46, group: "DrumKit" },
  { id: "VocalEffectsKit", label: "VocalEffectsKit", msb: 126, lsb: 0, programYamaha: 110, group: "DrumKit" },
  { id: "VocalBeatbox", label: "VocalBeatbox", msb: 126, lsb: 0, programYamaha: 107, group: "DrumKit" },
  { id: "PopLatinKit2Comp", label: "PopLatinKit2Comp", msb: 126, lsb: 0, programYamaha: 47, group: "DrumKit" },
  { id: "EDM Kit", label: "EDM Kit", msb: 127, lsb: 0, programYamaha: 70, group: "DrumKit" },
  { id: "80sPopKit", label: "80sPopKit", msb: 127, lsb: 0, programYamaha: 67, group: "DrumKit" },
  { id: "80sR&B Kit", label: "80sR&B Kit", msb: 127, lsb: 0, programYamaha: 68, group: "DrumKit" },
  { id: "DubstepKit", label: "DubstepKit", msb: 127, lsb: 0, programYamaha: 69, group: "DrumKit" },
  { id: "ElectroKit", label: "ElectroKit", msb: 127, lsb: 0, programYamaha: 71, group: "DrumKit" },
  { id: "SchlagerKit", label: "SchlagerKit", msb: 127, lsb: 0, programYamaha: 73, group: "DrumKit" },
  { id: "BassDrumKit", label: "BassDrumKit", msb: 126, lsb: 0, programYamaha: 21, group: "DrumKit" },
  { id: "RealDrumKit", label: "RealDrumKit", msb: 127, lsb: 0, programYamaha: 92, group: "DrumKit" },
  { id: "RealBrushesKit", label: "RealBrushesKit", msb: 127, lsb: 0, programYamaha: 42, group: "DrumKit" },
  { id: "AcousticKit", label: "AcousticKit", msb: 127, lsb: 0, programYamaha: 90, group: "DrumKit" },
  { id: "RockKit2", label: "RockKit2", msb: 127, lsb: 0, programYamaha: 91, group: "DrumKit" },
  { id: "StudioKit", label: "StudioKit", msb: 127, lsb: 0, programYamaha: 87, group: "DrumKit" },
  { id: "PowerKit1", label: "PowerKit1", msb: 127, lsb: 0, programYamaha: 88, group: "DrumKit" },
  { id: "PowerKit2", label: "PowerKit2", msb: 127, lsb: 0, programYamaha: 89, group: "DrumKit" },
  { id: "RoomKit", label: "RoomKit", msb: 127, lsb: 0, programYamaha: 9, group: "DrumKit" },
  { id: "JazzKit", label: "JazzKit", msb: 127, lsb: 0, programYamaha: 33, group: "DrumKit" },
  { id: "StandardKit", label: "StandardKit", msb: 127, lsb: 0, programYamaha: 1, group: "DrumKit" },
  { id: "AnalogT8Kit", label: "AnalogT8Kit", msb: 127, lsb: 0, programYamaha: 59, group: "DrumKit" },
  { id: "AnalogT9Kit", label: "AnalogT9Kit", msb: 127, lsb: 0, programYamaha: 60, group: "DrumKit" },
  { id: "BreakKit", label: "BreakKit", msb: 127, lsb: 0, programYamaha: 58, group: "DrumKit" },
  { id: "HipHopKit", label: "HipHopKit", msb: 127, lsb: 0, programYamaha: 57, group: "DrumKit" },
  { id: "DanceKit", label: "DanceKit", msb: 127, lsb: 0, programYamaha: 28, group: "DrumKit" },
  { id: "AnalogKit", label: "AnalogKit", msb: 127, lsb: 0, programYamaha: 26, group: "DrumKit" },
  { id: "HouseKit", label: "HouseKit", msb: 127, lsb: 0, programYamaha: 61, group: "DrumKit" },
  { id: "DrumMachine", label: "DrumMachine", msb: 127, lsb: 0, programYamaha: 62, group: "DrumKit" },
  { id: "HitKit", label: "HitKit", msb: 127, lsb: 0, programYamaha: 5, group: "DrumKit" },
  { id: "ReverseBD Kit", label: "ReverseBD Kit", msb: 126, lsb: 0, programYamaha: 22, group: "DrumKit" },
  { id: "TurkishKit", label: "TurkishKit", msb: 126, lsb: 0, programYamaha: 68, group: "DrumKit" },
  { id: "CubanKit", label: "CubanKit", msb: 126, lsb: 0, programYamaha: 41, group: "DrumKit" },
  { id: "PopLatinKit1", label: "PopLatinKit1", msb: 126, lsb: 0, programYamaha: 44, group: "DrumKit" },
  { id: "PopLatinKit2", label: "PopLatinKit2", msb: 126, lsb: 0, programYamaha: 45, group: "DrumKit" },
  { id: "SymphonyKit", label: "SymphonyKit", msb: 127, lsb: 0, programYamaha: 49, group: "DrumKit" },
  { id: "NewSFX Kit1", label: "NewSFX Kit1", msb: 126, lsb: 0, programYamaha: 3, group: "DrumKit" },
  { id: "NewSFX Kit2", label: "NewSFX Kit2", msb: 126, lsb: 0, programYamaha: 4, group: "DrumKit" },
  { id: "GospelAdLibs", label: "GospelAdLibs", msb: 126, lsb: 0, programYamaha: 111, group: "DrumKit" },
  { id: "RockDrumKit", label: "RockDrumKit", msb: 127, lsb: 8, programYamaha: 18, group: "Legacy" },
  { id: "PopDrumKit", label: "PopDrumKit", msb: 127, lsb: 8, programYamaha: 74, group: "Legacy" },
  { id: "VintageOpenKit2", label: "VintageOpenKit2", msb: 127, lsb: 8, programYamaha: 75, group: "Legacy" },
  { id: "VintageMutedKit", label: "VintageMutedKit", msb: 127, lsb: 8, programYamaha: 78, group: "Legacy" },
  { id: "JazzStickKit2", label: "JazzStickKit2", msb: 127, lsb: 8, programYamaha: 79, group: "Legacy" },
  { id: "JazzBrushExpanded", label: "JazzBrushExpanded", msb: 127, lsb: 8, programYamaha: 77, group: "Legacy" },
  { id: "JazzBrushKitComp", label: "JazzBrushKitComp", msb: 127, lsb: 8, programYamaha: 76, group: "Legacy" },
  { id: "StandardKit2", label: "StandardKit2", msb: 127, lsb: 0, programYamaha: 2, group: "Legacy" },
  { id: "BrushKit", label: "BrushKit", msb: 127, lsb: 0, programYamaha: 41, group: "Legacy" },
  { id: "RockKit3", label: "RockKit3", msb: 127, lsb: 0, programYamaha: 17, group: "Legacy" },
  { id: "TrapKit2", label: "TrapKit2", msb: 127, lsb: 0, programYamaha: 72, group: "Legacy" },
  { id: "ElectroKit2", label: "ElectroKit2", msb: 127, lsb: 0, programYamaha: 25, group: "Legacy" },
  { id: "CymbalKit", label: "CymbalKit", msb: 126, lsb: 0, programYamaha: 50, group: "Legacy" },
  { id: "ArabicKit", label: "ArabicKit", msb: 126, lsb: 0, programYamaha: 36, group: "Legacy" },
  { id: "SFX Kit1", label: "SFX Kit1", msb: 126, lsb: 0, programYamaha: 1, group: "Legacy" },
  { id: "SFX Kit2", label: "SFX Kit2", msb: 126, lsb: 0, programYamaha: 2, group: "Legacy" },
  { id: "NoisesKit", label: "NoisesKit", msb: 126, lsb: 0, programYamaha: 9, group: "Legacy" },
  { id: "SeaShore", label: "SeaShore", msb: 104, lsb: 0, programYamaha: 123, group: "Legacy" },
  { id: "Helicopter", label: "Helicopter", msb: 104, lsb: 0, programYamaha: 126, group: "Legacy" },
  { id: "Applause1", label: "Applause1", msb: 104, lsb: 0, programYamaha: 127, group: "Legacy" },
  { id: "Applause2", label: "Applause2", msb: 104, lsb: 1, programYamaha: 127, group: "Legacy" },
  { id: "GunShot", label: "GunShot", msb: 104, lsb: 0, programYamaha: 128, group: "Legacy" },
]

export const DEFAULT_BASS_VOICE_ID = "ElectricBass"
export const DEFAULT_GUITAR_VOICE_ID = "SolidGuitar1"
export const DEFAULT_DRUM_KIT_ID = "StandardKit"

export function findVoiceChoice(list: VoiceChoice[], id: string): VoiceChoice {
  return list.find((v) => v.id === id) || list[0]
}
